unittest_json: fix error with devel Nim
Before this commit, compiling `unittest_json` with a development version
of Nim (more recent than 2021-04-26) would produce:

    Error: undeclared identifier: '<//>'

This is because `<//>` was removed from Nim upstream. See:
- https://github.com/nim-lang/Nim/commit/68e522ececdb