Test: Improve `pass/multiple_tests_output_truncated`
Changes:
- Check the truncation behaviour for 499, 500 and 501 characters,
  rather than just 500, making use of the multiple tests. We can see
  this is useful because the initial implementation had an off-by-one
  error: output of exactly rune-length 500 did output all 500 runes,
  but then said incorrectly that the output was truncated. This is
  fixed in a later commit.
- Use digits rather than letters, which makes it easier to recognise the
  length of the strings in the test file. In particular, it was
  previously unexpected that an apparent `a..z` omits the letter `f` -
  it was confusing that the string ended in "z... output is truncated",
  because the alphabet is 26 letters long and 500 isn't divisible by 26.

I think `_123456789` is clearer than the full `a..z`: because with
"xyzabcdef... output is truncated" it's less obvious that 'f' is the
500th character. The reader shouldn't need to divide 500 by 26 and work
out the remainder is 6 to see that 'f', as the 6th letter of the
alphabet, is correct.

Using `_123456789` also improves consistency if we use "unicode numbers"
in the unicode truncation test.